const http = require('http');

function postJson(url, payload) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const data = JSON.stringify(payload);
    const req = http.request({
      hostname: u.hostname,
      port: u.port || 3000,
      path: u.pathname + u.search,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data)
      }
    }, res => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(body));
        } catch (e) {
          resolve({ raw: body });
        }
      });
    });
    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

function getJson(url) {
  return new Promise((resolve, reject) => {
    http.get(url, res => {
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => {
        try {
          resolve(JSON.parse(body));
        } catch (e) {
          resolve({ raw: body });
        }
      });
    }).on('error', reject);
  });
}

async function testHttpSubmit() {
  console.log('1. Requesting fresh assessment session for "Frontend Developer"...');
  const qData = await getJson('http://localhost:3000/api/assessment/questions?role=Frontend%20Developer');
  console.log('Session ID generated by server:', qData.sessionId);
  console.log('Total questions received:', qData.questions.length);

  // We need to know which option is correct to submit 17 correct answers (85%).
  // Let's test answers:
  // In the real app, each question has 4 options.
  // Let's see: how can our test find the correct option?
  // We can submit each question and test the grading.
  // Or we can check the server logs.
  console.log('\n2. Submitting assessment to /api/assessment/submit with sessionId...');
  
  // Let's create an answer payload for all 20 questions:
  const answers = {};
  qData.questions.forEach((q, i) => {
    answers[q.id] = 0; // select option index 0
  });

  const submitRes = await postJson('http://localhost:3000/api/assessment/submit', {
    candidateId: 'cand-http-' + Date.now(),
    candidateName: 'Vageesha Sharma',
    candidateEmail: 'sharmavageesha2000@gmail.com',
    roleApplied: 'Frontend Developer',
    sessionId: qData.sessionId,
    answers,
    tabSwitchesCount: 0,
    timeSpentSeconds: 300,
    forcedByViolation: false
  });

  console.log('\n3. Server Submission Response:');
  console.log('Success:', submitRes.success);
  console.log('Score:', submitRes.scorePercent + '%');
  console.log('Passed:', submitRes.passed);
  console.log('Verdict:', submitRes.verdict);
  console.log('Total Questions Evaluated:', submitRes.totalQuestions);
  console.log('Correct Count:', submitRes.correctCount);
  console.log('Incorrect Count:', submitRes.incorrectCount);
  if (submitRes.emailDispatched) {
    console.log('Email Dispatched:', submitRes.emailDispatched.subject, '| Message ID:', submitRes.emailDispatched.messageId);
  }
}

testHttpSubmit().catch(console.error);
